modLoader="javafml"
loaderVersion="[63,)"
license="All Rights Reserved"

[[mods]]
modId="bilibilichatmcforge"
version="${mod_version}"
displayName="BLChat"
displayURL="https://github.com/JeffreyMing2004"
authors="JeffreyMing"
description='''A tool for viewing danmaku in MC'''
clientSideOnly=true

[[dependencies.bilibilichatmcforge]]
    modId="forge"
    mandatory=true
    versionRange="[63,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bilibilichatmcforge]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.1.1,26.1.2,)"
    ordering="NONE"
    side="BOTH"
