org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.10
minecraft_version_range=[1.21.6,1.21.11)
forge_version=60.1.13
forge_version_range=[56,61)
loader_version_range=[56,61)
mapping_channel=official
mapping_version=1.21.10
mod_id=bilibilichatmcforge
mod_name=BLChat
mod_license=LGPL-2.1
mod_group_id=net.ming
mod_authors=JeffreyMing
mod_description=A tool for viewing danmaku in MC
